ALTER TABLE ONLY public.account_inventory ADD CONSTRAINT account_inventory_authorized_by_fkey FOREIGN KEY (authorized_by) REFERENCES public.profiles(id);
ALTER TABLE ONLY public.breach_management_team ADD CONSTRAINT breach_management_team_member_fkey FOREIGN KEY (member) REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.csba_answers ADD CONSTRAINT csba_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.csba_master(question_id);
ALTER TABLE ONLY public.csba_answers ADD CONSTRAINT csba_answers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
ALTER TABLE ONLY public.customer_product_licenses ADD CONSTRAINT customer_product_licenses_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.customer_product_licenses ADD CONSTRAINT customer_product_licenses_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.departments ADD CONSTRAINT departments_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.profiles(id);
ALTER TABLE ONLY public.document_assignments ADD CONSTRAINT document_assignments_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(document_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.document_departments ADD CONSTRAINT document_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.document_departments ADD CONSTRAINT document_departments_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(document_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.document_roles ADD CONSTRAINT document_roles_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(document_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.document_roles ADD CONSTRAINT document_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(role_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.document_users ADD CONSTRAINT document_users_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(document_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.email_layouts ADD CONSTRAINT email_layouts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.email_notifications ADD CONSTRAINT email_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.email_preferences ADD CONSTRAINT email_preferences_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.email_preferences ADD CONSTRAINT email_preferences_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.email_templates ADD CONSTRAINT email_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.email_templates ADD CONSTRAINT email_templates_layout_id_fkey FOREIGN KEY (layout_id) REFERENCES public.email_layouts(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.user_profile_roles ADD CONSTRAINT fk_user_profile_roles_role_id FOREIGN KEY (role_id) REFERENCES public.roles(role_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.hardware_inventory ADD CONSTRAINT hardware_inventory_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.hib_checklist ADD CONSTRAINT hib_checklist_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.hib_results ADD CONSTRAINT hib_results_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.key_dates ADD CONSTRAINT key_dates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id);
ALTER TABLE ONLY public.key_dates ADD CONSTRAINT key_dates_modified_by_fkey FOREIGN KEY (modified_by) REFERENCES public.profiles(id);
ALTER TABLE ONLY public.learning_track_assignments ADD CONSTRAINT learning_track_assignments_learning_track_id_fkey FOREIGN KEY (learning_track_id) REFERENCES public.learning_tracks(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.learning_track_department_assignments ADD CONSTRAINT learning_track_department_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.learning_track_department_assignments ADD CONSTRAINT learning_track_department_assignments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.learning_track_department_assignments ADD CONSTRAINT learning_track_department_assignments_learning_track_id_fkey FOREIGN KEY (learning_track_id) REFERENCES public.learning_tracks(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.learning_track_lessons ADD CONSTRAINT learning_track_lessons_learning_track_id_fkey FOREIGN KEY (learning_track_id) REFERENCES public.learning_tracks(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.learning_track_lessons ADD CONSTRAINT learning_track_lessons_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.learning_track_role_assignments ADD CONSTRAINT learning_track_role_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.learning_track_role_assignments ADD CONSTRAINT learning_track_role_assignments_learning_track_id_fkey FOREIGN KEY (learning_track_id) REFERENCES public.learning_tracks(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.learning_track_role_assignments ADD CONSTRAINT learning_track_role_assignments_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(role_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.learning_tracks ADD CONSTRAINT learning_tracks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.lesson_answer_translations ADD CONSTRAINT lesson_answer_translations_answer_id_fkey FOREIGN KEY (answer_id) REFERENCES public.lesson_answers(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_answer_translations ADD CONSTRAINT lesson_answer_translations_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.lesson_answer_translations ADD CONSTRAINT lesson_answer_translations_translated_by_fkey FOREIGN KEY (translated_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.lesson_answers ADD CONSTRAINT lesson_answers_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.lesson_nodes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_node_translations ADD CONSTRAINT lesson_node_translations_language_code_fkey FOREIGN KEY (language_code) REFERENCES public.languages(code);
ALTER TABLE ONLY public.lesson_node_translations ADD CONSTRAINT lesson_node_translations_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.lesson_nodes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_node_translations ADD CONSTRAINT lesson_node_translations_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.lesson_node_translations ADD CONSTRAINT lesson_node_translations_translated_by_fkey FOREIGN KEY (translated_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.lesson_nodes ADD CONSTRAINT lesson_nodes_embedded_lesson_id_fkey FOREIGN KEY (embedded_lesson_id) REFERENCES public.lessons(id);
ALTER TABLE ONLY public.lesson_nodes ADD CONSTRAINT lesson_nodes_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_reminder_counts ADD CONSTRAINT lesson_reminder_counts_learning_track_id_fkey FOREIGN KEY (learning_track_id) REFERENCES public.learning_tracks(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_reminder_counts ADD CONSTRAINT lesson_reminder_counts_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_reminder_counts ADD CONSTRAINT lesson_reminder_counts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_reminder_history ADD CONSTRAINT lesson_reminder_history_email_notification_id_fkey FOREIGN KEY (email_notification_id) REFERENCES public.email_notifications(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.lesson_reminder_history ADD CONSTRAINT lesson_reminder_history_learning_track_id_fkey FOREIGN KEY (learning_track_id) REFERENCES public.learning_tracks(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_reminder_history ADD CONSTRAINT lesson_reminder_history_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_reminder_history ADD CONSTRAINT lesson_reminder_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_translations ADD CONSTRAINT lesson_translations_language_code_fkey FOREIGN KEY (language_code) REFERENCES public.languages(code);
ALTER TABLE ONLY public.lesson_translations ADD CONSTRAINT lesson_translations_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_translations ADD CONSTRAINT lesson_translations_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.lesson_translations ADD CONSTRAINT lesson_translations_translated_by_fkey FOREIGN KEY (translated_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.lessons ADD CONSTRAINT lessons_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.lessons ADD CONSTRAINT lessons_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.notification_history ADD CONSTRAINT notification_history_email_template_id_fkey FOREIGN KEY (email_template_id) REFERENCES public.email_templates(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.notification_history ADD CONSTRAINT notification_history_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES public.notification_rules(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.notification_history ADD CONSTRAINT notification_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.notification_rules ADD CONSTRAINT notification_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.notification_rules ADD CONSTRAINT notification_rules_email_template_id_fkey FOREIGN KEY (email_template_id) REFERENCES public.email_templates(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.periodic_reviews ADD CONSTRAINT periodic_reviews_log_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id);
ALTER TABLE ONLY public.periodic_reviews ADD CONSTRAINT periodic_reviews_log_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.profiles(id);
ALTER TABLE ONLY public.physical_location_access ADD CONSTRAINT physical_location_access_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id);
ALTER TABLE ONLY public.physical_location_access ADD CONSTRAINT physical_location_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_language_fkey FOREIGN KEY (language) REFERENCES public.languages(display_name);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_manager_fkey FOREIGN KEY (manager) REFERENCES public.user_roles(user_id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_manager_fkey1 FOREIGN KEY (manager) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE ONLY public.quiz_attempts ADD CONSTRAINT quiz_attempts_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.roles ADD CONSTRAINT roles_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.template_variable_translations ADD CONSTRAINT template_variable_translations_variable_id_fkey FOREIGN KEY (variable_id) REFERENCES public.template_variables(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.template_variables ADD CONSTRAINT template_variables_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.translation_change_log ADD CONSTRAINT translation_change_log_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);
ALTER TABLE ONLY public.translation_change_log ADD CONSTRAINT translation_change_log_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.translation_jobs ADD CONSTRAINT translation_jobs_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);
ALTER TABLE ONLY public.translation_jobs ADD CONSTRAINT translation_jobs_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.translation_jobs ADD CONSTRAINT translation_jobs_target_language_fkey FOREIGN KEY (target_language) REFERENCES public.languages(code);
ALTER TABLE ONLY public.user_answer_responses ADD CONSTRAINT user_answer_responses_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.user_answer_responses ADD CONSTRAINT user_answer_responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.user_behavior_analytics ADD CONSTRAINT user_behavior_analytics_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.user_deletion_audit ADD CONSTRAINT user_deletion_audit_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.user_deletion_audit ADD CONSTRAINT user_deletion_audit_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.user_departments ADD CONSTRAINT user_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.user_learning_track_progress ADD CONSTRAINT user_learning_track_progress_learning_track_id_fkey FOREIGN KEY (learning_track_id) REFERENCES public.learning_tracks(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.user_lesson_progress ADD CONSTRAINT user_lesson_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.user_lesson_progress ADD CONSTRAINT user_lesson_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id);
ALTER TABLE ONLY public.user_phishing_scores ADD CONSTRAINT user_phishing_scores_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.product_license_assignments ADD CONSTRAINT user_product_licenses_license_id_fkey FOREIGN KEY (license_id) REFERENCES public.customer_product_licenses(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.product_license_assignments ADD CONSTRAINT user_product_licenses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
